name: Ubuntu CI

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install Qt
      run: sudo apt install qt5-default -y
    - name: Build Ubuntu
      run: |
        qmake
        make -j8

